In [1]:
!nvidia-smi

Tue Apr 23 03:45:28 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB           Off| 00000000:07:00.0 Off |                    0 |
| N/A   64C    P0              306W / 400W|  79962MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB           Off| 00000000:0F:00.0 Off |                    0 |
| N/A   69C    P0              373W / 400W|  64378MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB           Off| 00000000:47:00.0 Off |                    0 |
| N/A   67C    P0              404W / 400W|  53914MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB           Off| 00000000:4E:00.0 Off |                    0 |
| N/A   66C    P0              400W / 400W|  52224MiB / 81920MiB |     99%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM4-80GB           Off| 00000000:87:00.0 Off |                    0 |
| N/A   53C    P0              107W / 400W|   9508MiB / 81920MiB |     40%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM4-80GB           Off| 00000000:90:00.0 Off |                    0 |
| N/A   49C    P0               70W / 400W|      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM4-80GB           Off| 00000000:B7:00.0 Off |                    0 |
| N/A   47C    P0               66W / 400W|      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM4-80GB           Off| 00000000:BD:00.0 Off |                    0 |
| N/A   47C    P0               68W / 400W|      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2977525      C   python                                    78634MiB |
|    0   N/A  N/A   4126647      C   ...nh/python_venv/3.10_venv/bin/python     1326MiB |
|    1   N/A  N/A   2979633      C   /usr/bin/python                           64376MiB |
|    2   N/A  N/A   2979634      C   /usr/bin/python                           53912MiB |
|    3   N/A  N/A   2979635      C   /usr/bin/python                           52222MiB |
|    4   N/A  N/A   3709912      C   python3                                    2004MiB |
|    4   N/A  N/A   3726413      C   ...e/minhnh/python_venv/nlp/bin/python     7502MiB |
+---------------------------------------------------------------------------------------+

In [2]:
import torch
print(torch.__version__)

2.2.2+cu121

In [3]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "5"

In [4]:
torch.cuda.device_count()

1

In [1]:
from datasets import load_dataset, Dataset, DatasetDict
import pandas as pd
import torch
import transformers
import os
import argparse
import bitsandbytes as bnb
from functools import partial
import os
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, AutoPeftModelForCausalLM, PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed, Trainer, TrainingArguments, BitsAndBytesConfig, \
    DataCollatorForLanguageModeling, Trainer, TrainingArguments, BloomForCausalLM, BloomTokenizerFast, pipeline, \
    EarlyStoppingCallback
from accelerate import dispatch_model, infer_auto_device_map
from accelerate.utils import get_balanced_memory
from huggingface_hub.hf_api import HfFolder

/home/minhnh/python_venv/nlp/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-05-04 02:24:31.118402: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-04 02:24:31.954171: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [3]:
from huggingface_hub import login

login("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")

import datasets
import pandas as pd

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /raid/phundh/.cache/huggingface/token
Login successful

In [7]:
dataset = datasets.load_dataset("teknium/openhermes")

In [8]:
dataset

DatasetDict({
    train: Dataset({
        features: ['input', 'output', 'instruction'],
        num_rows: 242831
    })
})

In [9]:
dataset['train']['instruction'][0]

'Write a Perl script that processes a log file and counts the occurrences of different HTTP status codes. The script should accept the log file path as a command-line argument and print the results to the console in descending order of frequency.\n'

**meaning level**

In [11]:
import torch
from transformers import AutoModel, AutoTokenizer

deberta = AutoModel.from_pretrained("microsoft/deberta-v3-base")
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-v3-base")

/home/minhnh/python_venv/nlp/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:550: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

In [12]:
instruction_df = pd.DataFrame({"instruction": dataset['train']["instruction"]})

In [13]:
instruction_df.head()

                                         instruction
0  Write a Perl script that processes a log file ...
1  What can be seen once in a minute, twice in a ...
2  Famous inventors and their inventions: Identif...
3  Generate a list of 12 words that start with 'qu'.
4  Who was the first woman to win a Nobel Prize, ...

In [14]:
!ls -lh

total 1.4M
-rw-rw-r--+ 1 phundh phundh  38K Apr 23 03:55 clustering-Copy1.ipynb
-rw-r--r--  1 phundh phundh  34K Apr 23 03:53 clustering.ipynb
-rw-r--r--  1 phundh phundh 1.3M Apr 23 03:43 Kmeans.ipynb

In [16]:
from tqdm import tqdm

deberta.to('cuda:0')
list_emb = []
for i in tqdm(range(len(instruction_df["instruction"]))):
    input_ids = torch.tensor([tokenizer.encode(instruction_df["instruction"][i],truncation=True, max_length=254)])

    with torch.no_grad():
      features = deberta(input_ids.to('cuda:0'))
    list_emb.append((i,features))

100%|██████████| 242831/242831 [1:01:39<00:00, 65.63it/s]

In [17]:
import pickle

len_emb = len(list_emb)
print(len_emb)
list_emb_1 = [(i,ele[0][:, 0, :].to('cpu').numpy()) for i,ele in list_emb]
list_emb_2 = [(i,ele.squeeze(0)) for i,ele in list_emb_1]
# with open("my_array_word.pickle", "wb") as f:
#     pickle.dump(list_emb_2, f)

242831

In [18]:
import json
import numpy as np

list_data = []
for i,emb in list_emb_2:
    list_data.append({
        'index' : i,
        'emb' : emb
    })

In [23]:
from datasets import Dataset
from huggingface_hub import create_repo

df = pd.DataFrame(list_data)

HfFolder.save_token('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')
create_repo("AnhTong/openhermes_embeddings", repo_type="dataset", private=True)
dataset = Dataset.from_pandas(df.reset_index(drop=True))
dataset.push_to_hub("AnhTong/openhermes_embeddings")

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]
Creating parquet from Arrow format:   0%|          | 0/122 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   4%|▍         | 5/122 [00:00<00:02, 43.05ba/s]
Creating parquet from Arrow format:   8%|▊         | 10/122 [00:00<00:02, 44.12ba/s]
Creating parquet from Arrow format:  12%|█▏        | 15/122 [00:00<00:02, 44.31ba/s]
Creating parquet from Arrow format:  16%|█▋        | 20/122 [00:00<00:02, 44.14ba/s]
Creating parquet from Arrow format:  20%|██        | 25/122 [00:00<00:02, 43.82ba/s]
Creating parquet from Arrow format:  25%|██▍       | 30/122 [00:00<00:02, 43.81ba/s]
Creating parquet from Arrow format:  29%|██▊       | 35/122 [00:00<00:01, 44.31ba/s]
Creating parquet from Arrow format:  33%|███▎      | 40/122 [00:00<00:02, 40.14ba/s]
Creating parquet from Arrow format:  37%|███▋      | 45/122 [00:01<00:01, 41.68ba/s]
Creating parquet from Arrow format:  41%|████      | 50/122 [00:01<00:01, 42.74ba/s]
Creating parquet from Arrow format:  45%|████▌     | 55/122 [00:01<00:01, 43.24ba/s]
Creating parquet from Arrow format:  49%|████▉     | 60/122 [00:01<00:01, 43.69ba/s]
Creating parquet from Arrow format:  53%|█████▎    | 65/122 [00:01<00:01, 43.69ba/s]
Creating parquet from Arrow format:  57%|█████▋    | 70/122 [00:01<00:01, 43.82ba/s]
Creating parquet from Arrow format:  61%|██████▏   | 75/122 [00:01<00:01, 42.30ba/s]
Creating parquet from Arrow format:  66%|██████▌   | 80/122 [00:01<00:01, 41.90ba/s]
Creating parquet from Arrow format:  70%|██████▉   | 85/122 [00:01<00:00, 41.08ba/s]
Creating parquet from Arrow format:  74%|███████▍  | 90/122 [00:02<00:00, 40.75ba/s]
Creating parquet from Arrow format:  78%|███████▊  | 95/122 [00:02<00:00, 41.09ba/s]
Creating parquet from Arrow format:  82%|████████▏ | 100/122 [00:02<00:00, 41.01ba/s]
Creating parquet from Arrow format:  86%|████████▌ | 105/122 [00:02<00:00, 40.99ba/s]
Creating parquet from Arrow format:  90%|█████████ | 110/122 [00:02<00:00, 41.28ba/s]
Creating parquet from Arrow format:  94%|█████████▍| 115/122 [00:02<00:00, 40.43ba/s]
Creating parquet from Arrow format: 100%|██████████| 122/122 [00:02<00:00, 42.13ba/s]
Uploading the dataset shards:  50%|█████     | 1/2 [00:16<00:16, 16.62s/it]
Creating parquet from Arrow format:   0%|          | 0/122 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   3%|▎         | 4/122 [00:00<00:03, 36.35ba/s]
Creating parquet from Arrow format:   7%|▋         | 9/122 [00:00<00:02, 39.21ba/s]
Creating parquet from Arrow format:  11%|█▏        | 14/122 [00:00<00:02, 40.13ba/s]
Creating parquet from Arrow format:  16%|█▌        | 19/122 [00:00<00:02, 40.41ba/s]
Creating parquet from Arrow format:  20%|█▉        | 24/122 [00:00<00:02, 40.11ba/s]
Creating parquet from Arrow format:  24%|██▍       | 29/122 [00:00<00:02, 40.52ba/s]
Creating parquet from Arrow format:  28%|██▊       | 34/122 [00:00<00:02, 40.68ba/s]
Creating parquet from Arrow format:  32%|███▏      | 39/122 [00:00<00:02, 40.78ba/s]
Creating parquet from Arrow format:  36%|███▌      | 44/122 [00:01<00:01, 41.16ba/s]
Creating parquet from Arrow format:  40%|████      | 49/122 [00:01<00:01, 40.59ba/s]
Creating parquet from Arrow format:  44%|████▍     | 54/122 [00:01<00:01, 41.06ba/s]
Creating parquet from Arrow format:  48%|████▊     | 59/122 [00:01<00:01, 41.64ba/s]
Creating parquet from Arrow format:  52%|█████▏    | 64/122 [00:01<00:01, 41.51ba/s]
Creating parquet from Arrow format:  57%|█████▋    | 69/122 [00:01<00:01, 41.80ba/s]
Creating parquet from Arrow format:  61%|██████    | 74/122 [00:01<00:01, 42.19ba/s]
Creating parquet from Arrow format:  65%|██████▍   | 79/122 [00:01<00:01, 42.31ba/s]
Creating parquet from Arrow format:  69%|██████▉   | 84/122 [00:02<00:00, 42.37ba/s]
Creating parquet from Arrow format:  73%|███████▎  | 89/122 [00:02<00:00, 42.49ba/s]
Creating parquet from Arrow format:  77%|███████▋  | 94/122 [00:02<00:00, 42.47ba/s]
Creating parquet from Arrow format:  81%|████████  | 99/122 [00:02<00:00, 42.27ba/s]
Creating parquet from Arrow format:  85%|████████▌ | 104/122 [00:02<00:00, 38.90ba/s]
Creating parquet from Arrow format:  89%|████████▉ | 109/122 [00:02<00:00, 39.82ba/s]
Creating parquet from Arrow format:  93%|█████████▎| 114/122 [00:02<00:00, 40.40ba/s]
Creating parquet from Arrow format: 100%|██████████| 122/122 [00:02<00:00, 40.74ba/s]
Uploading the dataset shards: 100%|██████████| 2/2 [00:32<00:00, 16.00s/it]

CommitInfo(commit_url='https://huggingface.co/datasets/AnhTong/openhermes_embeddings/commit/94dcf2fb28c99894ce83ca4d1212c07b6a24a3b7', commit_message='Upload dataset', commit_description='', oid='94dcf2fb28c99894ce83ca4d1212c07b6a24a3b7', pr_url=None, pr_revision=None, pr_num=None)

In [7]:
new_df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.167160,0.216815,0.017307,-0.082711,0.069943,-0.138898,-0.007116,0.130978,-0.266812,0.094869,...,-0.072348,0.088961,-0.041797,0.003700,-0.027893,-0.091257,0.015189,-0.038572,0.171006,0.045660
1,0.161700,0.188492,0.069968,-0.079411,0.079285,-0.142506,0.030513,0.096139,-0.177043,0.063567,...,-0.110703,0.047891,-0.053654,0.024492,-0.019001,-0.122804,-0.010448,-0.085868,0.161146,0.028608
2,0.126472,0.202549,0.057488,-0.074422,0.102608,-0.124456,-0.013718,0.096164,-0.187552,0.050649,...,-0.091656,0.056603,-0.056991,0.013226,-0.022421,-0.128855,0.028661,-0.063802,0.146356,0.029558
3,0.127189,0.204616,0.069314,-0.096737,0.108468,-0.153656,0.019333,0.106194,-0.193393,0.054897,...,-0.091340,0.055227,-0.053493,0.076894,-0.018282,-0.139868,0.025219,-0.059740,0.155294,0.025411
4,0.112836,0.206392,0.068531,-0.069745,0.081232,-0.132258,-0.007107,0.105987,-0.139373,0.058674,...,-0.084634,0.039178,-0.068761,0.022409,-0.014040,-0.124477,0.029374,-0.061451,0.151064,0.031979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242826,0.149646,0.202505,0.038390,-0.068289,0.063717,-0.120714,-0.015830,0.109444,-0.208738,0.090200,...,-0.090819,0.058249,-0.061483,-0.005634,-0.036754,-0.111629,0.030921,-0.063511,0.169066,0.035805
242827,0.149646,0.202505,0.038390,-0.068289,0.063717,-0.120714,-0.015830,0.109444,-0.208738,0.090200,...,-0.090819,0.058249,-0.061483,-0.005634,-0.036754,-0.111629,0.030921,-0.063511,0.169066,0.035805
242828,0.166723,0.230004,0.029435,-0.093976,0.085549,-0.117377,-0.015510,0.126864,-0.240355,0.070254,...,-0.088207,0.074450,-0.053059,0.025148,-0.015072,-0.103032,0.035398,-0.056681,0.193330,0.038322
242829,0.166723,0.230004,0.029435,-0.093976,0.085549,-0.117377,-0.015510,0.126864,-0.240355,0.070254,...,-0.088207,0.074450,-0.053059,0.025148,-0.015072,-0.103032,0.035398,-0.056681,0.193330,0.038322
242830,0.166723,0.230004,0.029435,-0.093976,0.085549,-0.117377,-0.015510,0.126864,-0.240355,0.070254,...,-0.088207,0.074450,-0.053059,0.025148,-0.015072,-0.103032,0.035398,-0.056681,0.193330,0.038322